### ISSUE TITLE
Ripgrep doesn`t always support PCRE2

### ISSUE THREAD

**Issue by AZanellato** [pechorin/any-jump.vim#14]
Hello! I managed to use the plugin by setting ag as the default engine, but didn't manage to use it with rg because my build of rg doesn't have PCRE2 support, which gives out the following error message:
```
Error detected while processing function <SNR>30_Jump[22]..search#SearchDefinitions[19]..<SNR>183_RunRgDefinitionSearch[5]..<SNR>183_Par
seRgResults:                                                                                                                            
line    7:                                                                                                                              
E474: Unidentified byte: PCRE2 is not available in this build of ripgrep                                                                
E474: Failed to parse PCRE2 is not available in this build of ripgrep 
```

I understand that maybe you don't want to support rg without PCRE2, but maybe a better error message?

Amazing plugin though!

**Comment by pechorin** [comment]
Hello, thanks for report. I will try to add PCRE2 check for better error message :)

Also i think too many any-jump regexps uses PCRE2, so this is not in my road-map, but i think i will research this problem.

**Comment by wookayin** [comment]
For future reference:

This often happens when one mistakenly have `rg` installed in their *anaconda* environments, which often supersedes in PATH. [The official prebuilt binaries](https://github.com/BurntSushi/ripgrep/releases) well support PCRE2.

**Comment by AZanellato** [comment]
Not only that. The installation through cargo doesn't support PCRE2 by default.

**Comment by BurntSushi** [comment]
If you're installing ripgrep with Cargo, you should be able to enable PCRE2 support via `cargo install ripgrep --features pcre2`.

Also, you all might consider using `--auto-hybrid-regex`. I don't know exactly how you're invoking ripgrep and what kind of regexes you're using, but enabling PCRE2 can be slower: https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#pcre2-slow (There are ways to make it faster, which the FAQ entry addresses.) However, if you use `--auto-hybrid-regex`, then ripgrep will automatically use its default engine if it can (when the regex doesn't have look-around or backreferences).

**Comment by pechorin** [comment]
Okay, not all regexp rules use PCRE2 look-ahed/behind so i think i can enable --auto-hybrid-regex instead of strict --PCRE2

https://github.com/pechorin/any-jump.vim/commit/be4b64a6d4bbd82f8c5b076bf28666f150eea13a

Please try and let me know if it helps :)

**Comment by AZanellato** [comment]
Thank you @pechorin and @BurntSushi !
