### ISSUE TITLE
Error when using in .scss file

### ISSUE THREAD

**Issue by deathmaz** [pechorin/any-jump.vim#20]
Hi, i'm getting the following 
![image](https://user-images.githubusercontent.com/6440135/76028847-15677680-5f3c-11ea-9d8b-46b1b12093fa.png)
when trying to use any-jump on .scss file.
Thanks for the nice work!

Edit: 
`
NVIM v0.5.0-nightly-514-g31614d3eb
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200209-16514-i4xv62/build/config -I/tmp/neovim-20200209-16514-i4xv62/src -I/usr/local/include -I/tmp/neovim-20200209-16514-i4xv62/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200209-16514-i4xv62/build/src/nvim/auto -I/tmp/neovim-20200209-16514-i4xv62/build/include
`

**Comment by deathmaz** [comment]
thanks you for the fix!

>Maybe i should make this behave dynamically for filetypes like css.

or another option would be to make a configuration to specify which filetypes should work in `full` mode

**Comment by deathmaz** [comment]
strange but when i'm doing `let g:any_jump_keyword_match_cursor_mode = 'full'` for `.scss` file i have this
![image](https://user-images.githubusercontent.com/6440135/76065032-7e2e0d80-5f93-11ea-9f96-f9b397ab2476.png)
without `let g:any_jump_keyword_match_cursor_mode = 'full'` i don't have the error

**Comment by pechorin** [comment]
@deathmaz i do rework on this part of plugin and now where is more proper way of selecting keyword: `g:any_jump_keyword_match_cursor_mode` is deprecated, use visual mode selection and same `<leader>j`. 

https://github.com/pechorin/any-jump.vim/commit/dd0d413984a427dcf6ac052a34221f9de3306e6a

**Comment by pechorin** [comment]
I think i fixed some problems in https://github.com/pechorin/any-jump.vim/commit/11c0fc991c716f8245c61ff39d73c815efe43961

Please update to this commit and let me know :)

**Comment by deathmaz** [comment]
works fine i think, thank you!
