### ISSUE TITLE
Ignore files not in git

### ISSUE THREAD

**Issue by tjwallace** [pechorin/any-jump.vim#22]
Is it possible to skip/ignore files that aren't tracked by git? I have some database/JSON dumps inside my project directory that make searching very slow.

**Comment by pechorin** [comment]
Will added this very soon.

**Comment by pechorin** [comment]
I think it fixed in https://github.com/pechorin/any-jump.vim/commit/59168eb78c6d48c62f0596416fdfe3e7e80f9e4f.

Please try to add to your vimrc:

```
call g:AnyJumpAddIgnoredFile('*.tmp')
call g:AnyJumpAddIgnoredFile('*.temp')
call g:AnyJumpAddIgnoredFile('tags')
```

**Comment by pechorin** [comment]
@tjwallace please notice what latest version of https://github.com/pechorin/any-jump.vim/commit/5a564e14eefa6e60c5dd304a52010a3391ffaa43 contains breaking change, where is no more `g:AnyJumpAddIgnoredFile` only `g:any_jump_ignored_files`.
