### ISSUE TITLE
Remove whitespace from result window

### ISSUE THREAD

**Issue by numbcoder** [pechorin/any-jump.vim#23]
Awesome plugin, but some colorschemes highlight the whitespace, it looks weird.

<img width="532" alt="WX20200306-130914@2x" src="https://user-images.githubusercontent.com/281076/76054621-3ebfeb00-5fac-11ea-84db-129408c6f69f.png">

**Comment by pechorin** [comment]
Thanks for response. Hmm, i should inspect this. Give me a little time.

**Comment by pechorin** [comment]
@numbcoder can you tell me the colorscheme name you use?

**Comment by numbcoder** [comment]
> @numbcoder can you tell me the colorscheme name you use?

https://github.com/joshdick/onedark.vim and https://github.com/ntpeters/vim-better-whitespace

**Comment by pechorin** [comment]
So, this is vim-better-whitespace effect :) fixed in https://github.com/pechorin/any-jump.vim/commit/1839b1a9e948be0a822c4c855d3cae55bd5e725e
