### ISSUE TITLE
auto close when vim updatetime trigger

### ISSUE THREAD

**Issue by fcying** [pechorin/any-jump.vim#25]
```
set updatetime=300  "default 4000
```
`<leader>j`,  and wait updatetime, popup window will be auto close.

nvim don't have this problem.

```
vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  6 2020 16:27:09)
Included patches: 1-357
```

**Comment by pechorin** [comment]
Hmm, i need to research on this.

**Comment by pechorin** [comment]
Thanks for report, fixed in https://github.com/pechorin/any-jump.vim/commit/47022db2dff6c1ff125f48d266c22cc81c876f5d
