### ISSUE TITLE
Windows GVim cannot open temp files

### ISSUE THREAD

**Issue by tactualjota** [pechorin/any-jump.vim#28]
When I call :AnyJump, I get the following error:
```
Error detected while processing function <SNR>13_Jump[30]..search#SearchDefinitions[28]..<SNR>109_RunRgDefinitionSearch:

E484: Can't open file C:/Users/jata/AppData/Local/Temp/VIo479B.tmp
```

This is on Windows, with GVim installed with Choco, and 'rg' as the search engine. The same code works on ubuntu.

**Comment by pechorin** [comment]
Thanks for report, will fix temp files soon

**Comment by pechorin** [comment]
I think it fixed in https://github.com/pechorin/any-jump.vim/commit/59168eb78c6d48c62f0596416fdfe3e7e80f9e4f

please check
