### ISSUE TITLE
Restricted s:RunRgUsagesSearch to search filetype only as s:RunAgDefinitionSearch

### ISSUE THREAD

**Issue by markwu** [pechorin/any-jump.vim#29]
Can we have an option to let  `s:RunRgUsagesSearch()` search same buffer filetype only  as `s:RunAgDefinitionSearch()` does.

I work with php project, and sometimes I have the same function name or class name in javascript.

If `s:RunRgUsagesSearch()` search for all filetypes, the result will become very big and annoying.

Therefore, I am asking for an option to let me search same buffer filetype only. 

Thanks.

**Comment by pechorin** [comment]
Thanks for response. I think this option is reasonable.

**Comment by pechorin** [comment]
I think i fix it in https://github.com/pechorin/any-jump.vim/commit/59168eb78c6d48c62f0596416fdfe3e7e80f9e4f.

Please try this:

```
" Search references only for current file type
" (default: false, so will find keyword in all filetypes)
let g:any_jump_references_only_for_current_filetype = 1
```

**Comment by markwu** [comment]
Thanks, it works perfect for me.
