### ISSUE TITLE
E20: Mark not set

### ISSUE THREAD

**Issue by shapovalovts** [pechorin/any-jump.vim#30]
When search in visual mode and then press Enter to jump to the definition, then it prints:
```

Error detected while processing function <SNR>94_VimPopupFilter[44]..AnyJumpHandleOpen:
line   30: E20: Mark not set
```

After that it opens the file correctly.

vim 8.2, Ubuntu 18.04.

**Comment by pechorin** [comment]
Thanks for report, i see this error twice ... but can't reproduce now. Sorry. Will try to find it and fix it

**Comment by pechorin** [comment]
Thanks for @neihc , fixed in https://github.com/pechorin/any-jump.vim/pull/37
