### ISSUE TITLE
Hard to see things with the Apprentice colorscheme

### ISSUE THREAD

**Issue by gfixler** [pechorin/any-jump.vim#32]
I'm using romainl's [Apprentice](https://github.com/romainl/Apprentice) colorscheme, but the text in the popup is hard to see.

![2020-03-07-000115_979x667_scrot](https://user-images.githubusercontent.com/1888391/76139661-2630ee80-6007-11ea-82af-dc6b519718ee.png)

**Comment by pechorin** [comment]
Now you can customize any color via:

let g:any_jump_colors = {
      \"plain_text":         "Comment",
      \"preview":            "Comment",
      \"preview_keyword":    "Operator",
      \"heading_text":       "Function",
      \"heading_keyword":    "Identifier",
      \"group_text":         "Comment",
      \"group_name":         "Function",
      \"more_button":        "Operator",
      \"more_explain":       "Comment",
      \"result_line_number": "Comment",
      \"result_text":        "Statement",
      \"result_path":        "String",
      \"help":               "Comment"
      \}

Added in 330b535
