### ISSUE TITLE
E474: Failed to parse zsh:1: no matches found

### ISSUE THREAD

**Issue by optixx** [pechorin/any-jump.vim#34]
- Using NVIM v0.4.3  on MacOS
- rg installed
- ag not installed
- default shell zsh
- When using `<leader>j` i get an error
<img width="764" alt="Screenshot 2020-03-07 at 13 39 37" src="https://user-images.githubusercontent.com/40823/76143619-3b466580-6079-11ea-9613-a8e81f96993a.png">

**Comment by Jayphen** [comment]
I'm getting the same error, it only started occurring in the past few days.

**Comment by pechorin** [comment]
Sorry for error and late response. Fixed in https://github.com/pechorin/any-jump.vim/commit/997bf77cb566fe187ebb41b3ce5c702d26686cf5

Please update plugin.
