### ISSUE TITLE
Add key bindings to open in a new split or tab

### ISSUE THREAD

**Issue by numbcoder** [pechorin/any-jump.vim#36]
Add key bindings <kbd>t</kbd> / <kbd>s</kbd> / <kbd>v</kbd> to open file in a new tab, a new split, or in a new vertical split

**Comment by pechorin** [comment]
Implemented in https://github.com/pechorin/any-jump.vim/commit/f181eff4f05baac6f8c335ba3ecd78dbbef298a8

thanks

**Comment by numbcoder** [comment]
awesome！
