### ISSUE TITLE
First releases feedback

### ISSUE THREAD

**Issue by pechorin** [pechorin/any-jump.vim#4]
Thanks for using first alpha releases. If you have any feedback about using this plugin/missing features/nice-staff-you-like and any other staff please let me know. This is very important for me.

In generally next big plan is:

- vim support
- "save search", "show 10 recent searches"
- ctags support

**Comment by pechorin** [comment]
@kujohn @wallace11 @wbthomason @wookayin please let me know if you have any feedback/ideas ;) Thanks!

**Comment by wookayin** [comment]
Here are some quick (and minor) opinions of mine. I'd be happy to create an individual issue for each enhancement/new-feature item.

- I don't think line numbers are necessary.
- Once a focus to the floating window is lost, the window should disappear. Like many other plugins with floating window.
- The keyword (symbols) should be highlighted (e.g. as in fzf or vim-clap).
- I wish lilename & line numbers would come before a preview of the line (as in Quickfix or Location windows of vim)
- A major new feature: Interactive filtering via FZF would be great. FYI: I have a similar rg-based jump command only for python (link: [my vimrc](https://github.com/wookayin/dotfiles/blob/master/vim/vimrc#L1078-L1103)). Thanks to fzf, I could enjoy more fine-grained filtering via fuzzy search and built-in previews with syntax highlighting.

**Comment by pechorin** [comment]
@wookayin 

Thanks for response, i will try to comment:

_>> I don't think line numbers are necessary._

+ Maybe you right, i also think about this, maybe disabling line numbers be default is okay for more compact UI.

_>> Once a focus to the floating window is lost, the window should disappear. Like many other plugins with floating window._

+ will implement this

_>> The keyword (symbols) should be highlighted (e.g. as in fzf or vim-clap)._

Already in my todo list, thanks :)

_>> I wish filename & line numbers would come before a preview of the line (as in Quickfix or Location windows of vim)_

You could try this:

```viml
let g:any_jump_results_ui_style = 'filename_last'
```

or

```viml
let g:any_jump_results_ui_style = 'filename_first'
```

So, this is configurable and as i understand right this will suite your needs?

_>>A major new feature: Interactive filtering via FZF would be great. FYI: I have a similar rg-based jump command only for python (link: my vimrc). Thanks to fzf, I could enjoy more fine-grained filtering via fuzzy search and built-in previews with syntax highlighting._

This is big area to think. FZF is really fast, and i don't think what providing results to fzf is a problem for implementation (as additional feature). I also think vimL-driven fzf-like engines is slow. Maybe lua could help, i don't know, will think about it.

**Comment by wadkar** [comment]
My very small 2 cents:

- I have observed and been told that it is a good practice to `augroup` your `aucmds`. So the documentation could be improved that shows keybindings for the floating window. For example,

---
Default mappings for popup search windows are as follows (feel free to override them):

```viml
augroup AnyJumpFileType
  au FileType any-jump nnoremap <buffer> o :call g:AnyJumpHandleOpen()<cr>
  au FileType any-jump nnoremap <buffer><CR> :call g:AnyJumpHandleOpen()<cr>
  " <snip>
augroup end
```

---

- I think it's much easy for most users to interpret `0`/`1` as `v:false`/`v:true`.

- I _really_ liked the help section at the bottom, which vastly improves the UX in my opinion. It would be great if the same is provided consistently. I like `Undotree` plugin in this regard - it always tells you (by default) what the `> .... <` or `* .... *` mean at the top.

**Comment by pechorin** [comment]
@wadkar 

_>> I have observed and been told that it is a good practice to augroup your aucmds._

Thanks, will do it :)

_>> I think it's much easy for most users to interpret 0/1 as v:false/v:true._

Yeah, you right, i will rewrite this.

_>> It would be great if the same is provided consistently._

Sorry, can't understand this. You mean ability to toggle help block? or about what? Sorry for misunderstanding again :)

**Comment by wadkar** [comment]
> Sorry, can't understand this. You mean ability to toggle help block? or about what? Sorry for misunderstanding again :)

Oh no, it's fine. I probably could've phrased it better.

What I meant to say was: by default the help block should be present consistently. This was more forward looking statement given the discussion around fzf and how it'll be a different UI for AnyJump.

**Comment by pechorin** [comment]
@wadkar so if i understand correct - you want ability to hide help block? :)

**Comment by wadkar** [comment]
Yes, an option would be nice. But more importantly, I wanted to show my appreciation for the thought process to improve user experience.

**Comment by pechorin** [comment]
Where are many improvements since. Please update plugin version and enjoy :)
