### ISSUE TITLE
`g:any_jump_results_ui_style` seems backwards

### ISSUE THREAD

**Issue by milogert** [pechorin/any-jump.vim#42]
In the following lines it seems as though you are reversing how `filename_first` and `filename_last` are operating. In practice this does seem to be the case.

https://github.com/pechorin/any-jump.vim/blob/6c434d27c3866a897fc8ebe1257fe36433bef4b0/autoload/internal_buffer.vim#L406-L421

Other than that, it's been a great plugin! Excellent with React/JSX dev!

**Comment by pechorin** [comment]
Thanks for error report :) fixed in https://github.com/pechorin/any-jump.vim/commit/98eea927468c1c1e6d376eca994862f404acaeb2
