### ISSUE TITLE
E474: unidentified byte error: found argument '--auto-hybrid-regex' which wasn't expected or isn't valid in this context

### ISSUE THREAD

**Issue by carelsarthur** [pechorin/any-jump.vim#43]
- Using nvim  0.5.0-nightly snap
- Rg installed
- Ag not installed
- Default bash shell

When doing :AnyJump I get the following error:
`Error detected while processing function <SNR>47_Jump[30]..search#SearchDefinitions[28]..<SNR>56_RunRgDefinitionSearch[8]..<SNR>56_ParseRgRe
sults:
line    7:
E474: Unidentified byte: error: Found argument '--auto-hybrid-regex' which wasn't expected, or isn't valid in this context
E474: Failed to parse error: Found argument '--auto-hybrid-regex' which wasn't expected, or isn't valid in this context
`

I have the following setting enabled in my init.vim:
`let g:any_jump_search_preferred_engine = 'rg'
let g:any_jump_ignored_files = ['*.tmp','*.temp']
`

**Comment by pechorin** [comment]
Hello @carelsarthur, thanks for report. Which version of rg do you use?

**Comment by carelsarthur** [comment]
When running rg --version I get the following output:
`ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
`

**Comment by pechorin** [comment]
--autho-hybrid-regexp added only in 11.0.0, i should notice this in readme, thanks
