### ISSUE TITLE
neovim: Error generating helptags: Mix of help file encodings within a language

### ISSUE THREAD

**Issue by b0o** [pechorin/any-jump.vim#46]
Neovim doesn't yet seem to support UTF-8 in help files. I get the following error message upon running `helptags`:

```
E670: Mix of help file encodings within a language: doc/any-jump.txt
```

Due to the `—`, `⚒`, and `🔬` chars on line 1. 

Related: 

https://github.com/ryanoasis/vim-devicons/issues/162
https://github.com/ryanoasis/vim-devicons/pull/178
https://github.com/ryanoasis/vim-devicons/pull/163
https://github.com/vim/vim/issues/2213
https://github.com/neovim/neovim/issues/7402

**Comment by pechorin** [comment]
Hello @b0o, thanks for report. Fixed in https://github.com/pechorin/any-jump.vim/commit/0bc35858f2b855cdb927f485fb75bb89850de439 :)

**Comment by pechorin** [comment]
@b0o please report if it helps or not

**Comment by b0o** [comment]
Fixed, thank you. I wish the emojis worked in all cases, they made the docs 10x cooler.
