### ISSUE TITLE
Colors don't look good for light theme

### ISSUE THREAD

**Issue by hoschi** [pechorin/any-jump.vim#49]
I saw that I can configure some colors, but not the main background color, is this correct? Light themes are hard to read at the moment:

peachpuff (built in)
![2020-03-15-170214_1356x1370_scrot](https://user-images.githubusercontent.com/163128/76705247-de812580-66de-11ea-96dd-f9e54e31d4d8.png)

[solarized](https://github.com/lifepillar/vim-solarized8)
![2020-03-15-170118_1356x1370_scrot](https://user-images.githubusercontent.com/163128/76705264-0a041000-66df-11ea-8957-6861d176a6a5.png)

**Comment by pechorin** [comment]
Yeah,  see what any-jump not looks good in solarizied. I think i fix it in near release, thanks for support. For me it was not obvious moment while i developed current versionn of any-jump cause primarly i used ~5 themes, but now i see i need to test it more on some popular themes, maybe do some special bindings for most popular themes. 

But currently you can configure your theme via `let g:any_jump_colors = {}`. Like this:

```
let g:any_jump_colors = {
      \"plain_text":         "Comment",
      \"preview":            "Comment",
      \"preview_keyword":    "Operator",
      \"heading_text":       "Function",
      \"heading_keyword":    "Identifier",
      \"group_text":         "Comment",
      \"group_name":         "Function",
      \"more_button":        "Operator",
      \"more_explain":       "Comment",
      \"result_line_number": "Comment",
      \"result_text":        "Statement",
      \"result_path":        "String",
      \"help":               "Comment"
      \}
```

If you find best combination for your themes please provide them with config and screen :) Thanks.

**Comment by nrupatunga** [comment]
Sorry for the less knowledge on this, 

Can you explain what these individual settings mean, 
```
let g:any_jump_colors = {
      \"plain_text":         "Comment",
      \"preview":            "Comment",
      \"preview_keyword":    "Operator",
      \"heading_text":       "Function",
      \"heading_keyword":    "Identifier",
      \"group_text":         "Comment",
      \"group_name":         "Function",
      \"more_button":        "Operator",
      \"more_explain":       "Comment",
      \"result_line_number": "Comment",
      \"result_text":        "Statement",
      \"result_path":        "String",
      \"help":               "Comment"
      \}
```

**Comment by nrupatunga** [comment]
Is there a way to change the pop-up screen background color?

**Comment by hoschi** [comment]
@nrupatunga you can map highlight groups to positions used in the plugin, e.g. "help" text should look like "Comment".
@pechorin I can't change the main background color with these settings, can I?

**Comment by nrupatunga** [comment]
Thank you @hoschi . I got the hang of it.

**Comment by cschneid** [comment]
I'm running into the same issue with illegible text on most of my themes. Can you control the color of the background of the popup box? The bright pink is not the best for most themes.

**Comment by zhouyangnk** [comment]
same problem,  Can I change the color of the background of the popup box?

**Comment by domi91c** [comment]
I'm unable to change the background color as well. It seems to be associated with the `Pmenu` highlight value, but I don't want to change completion menu's background colour if I don't need to.

**Comment by ryuta69** [comment]
Yeah same here.

**Comment by tengteng** [comment]
> I'm unable to change the background color as well. It seems to be associated with the `Pmenu` highlight value, but I don't want to change completion menu's background colour if I don't need to.

domi91c is right. It's `Pmenu` in vim colorscheme config.
e.g, change/add below line in your `~/.vimrc/colors/WHATEVER_COLORSCHEME_U_R_USING.vim`

`hi Pmenu ctermbg=gray guibg=gray`

Will change popup_menu color to gray.

**Comment by ryuta69** [comment]
@tengteng I knew that, but it would be better if you can change theme.
For example, you can switch highlight when you command each time by Cmdenter and Cmdleave. 
Just like that, if this plugin switch the highlight whenever the  menu popup, this achieves.

Maybe any other idea can do that, so just I'm hoping if this plugin suppports it

**Comment by pechorin** [comment]
I add section to readme about this problem:

https://github.com/pechorin/any-jump.vim/commit/a3c9ed3ef7f01ed188daf0c64a08bb1e474d3748

You should configure your Pmenu hl group. I try to find some ways to do local `hl Pmenu` but don't find anything usefull. Maybe nvim `winhl` can helps in some ways but i'm not sure.

So, thanks to all.
