### ISSUE TITLE
Arrow keys on plugin window.

### ISSUE THREAD

**Issue by bvicenzo** [pechorin/any-jump.vim#52]
First of all, congrats on doing this plugin!
I've started to use it and loved it!
I have an improvement suggestion.
Some people that use my .vim are learning and use the arrow keys on the keyboard to navigate.
However, it's not working in the plugin window.
Is there a possibility of it works?

Thank you for your attention :)

**Comment by pechorin** [comment]
Hello, @bvicenzo thanks for response and your suggestion, i think where is no problem with what, i will add what in near release.

**Comment by bvicenzo** [comment]
Very thanks.
