### ISSUE TITLE
Is it possible to exclude certain directories?

### ISSUE THREAD

**Issue by Blake-LeBlanc** [pechorin/any-jump.vim#53]
There are certain directories that I do *NOT* want any-jump to search through when looking for matches.

Is there currently any setting to exclude certain directories from search results?

Thank you again for your great plugin!

**Comment by pechorin** [comment]
Hello, @Blake-LeBlanc, can you try?

```
let g:any_jump_ignored_files = ['*.tmp', '*.temp', 'app/models']
```

**Comment by Blake-LeBlanc** [comment]
> Hello, @Blake-LeBlanc, can you try?
> 
> ```
> let g:any_jump_ignored_files = ['*.tmp', '*.temp', 'app/models']
> ```
> 
> I should add this to doc

That does the trick, thank you Andrey!
