### ISSUE TITLE
Is it support jump to the library function?

### ISSUE THREAD

**Issue by jen6** [pechorin/any-jump.vim#54]
Hi! It was so nice to use any-jump.vim. It increase my productivity a lot.
Is there feature like jump to the library function like installed from pip or else?
Or maybe have include path for finding references. 
I hope support this feature too

**Comment by pechorin** [comment]
@jen6 hello, thanks for report. This feature is in my roadmap and planned for next releases.
https://github.com/pechorin/any-jump.vim/issues/56
Thanks :)
