### ISSUE TITLE
The selection bar always starts at the bottom of the search popup window

### ISSUE THREAD

**Issue by kjkuan** [pechorin/any-jump.vim#58]
![dev_—_docker_—_266×61](https://user-images.githubusercontent.com/973329/79053794-eb296880-7c0d-11ea-9726-2f145bf4e249.png)

For some reason, the selection bar always starts at the bottom of the popup window (see screenshot above), so to select the first entry in this case I have to hit `j` three times to make it select the `s.rb:2 def a_method` line.

I'm using vim 8.2 (Included patches: 1-460) in a terminal.

**Comment by dsabsay** [comment]
This problem has bugged me for weeks, if not months. Finally sat down and fixed it. PR is open: #75

**Comment by pechorin** [comment]
Sorry for delay, review problems and try to fix them: https://github.com/pechorin/any-jump.vim/pull/75

**Comment by pechorin** [comment]
fixed in https://github.com/pechorin/any-jump.vim/pull/79
