### ISSUE TITLE
No C support ? (works with cpp rules)

### ISSUE THREAD

**Issue by pseregiet** [pechorin/any-jump.vim#70]
There is no C support, however, just copy pasting the cpp related code and renaming the name to 'c' works fine :)

**Comment by Sharlock93** [comment]
just changing the "filetype" in vim also makes it work

**Comment by pechorin** [comment]
yeah, i think c lang support is missing for now

**Comment by pechorin** [comment]
fixed in https://github.com/pechorin/any-jump.vim/pull/80
please update plugin and tell me if searching still not working
