### ISSUE TITLE
Is there a way to add border?

### ISSUE THREAD

**Issue by tami5** [pechorin/any-jump.vim#77]
Hi there, Is there a way to add border to the floating window. It is so hard to distinguish between the buffer and the floating window.
Thanks

**Comment by NightH4nter** [comment]
Second this. It would be very useful.

**Comment by pechorin** [comment]
Work on borders: https://github.com/pechorin/any-jump.vim/pull/74

**Comment by tami5** [comment]
@pechorin tried it, works very well, however an option to adjust the border value would be useful

**Comment by pechorin** [comment]
@tami5 i also think maybe it should have other border variants.

**Comment by kristijanhusak** [comment]
@tami5 check https://github.com/pechorin/any-jump.vim/pull/74#issuecomment-740437636 for details how to configure the border

**Comment by tami5** [comment]
Nice, thanks @kristijanhusak
